package com.flipkart.krystal.lattice.codegen.spi.di;

import static com.flipkart.krystal.lattice.codegen.DepInjectionFramework.NONE;

import com.flipkart.krystal.lattice.codegen.DepInjectionFramework;
import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.CodeBlock;
import com.squareup.javapoet.ParameterSpec;
import com.squareup.javapoet.TypeName;
import java.util.List;

/**
 * A binding whose value is provided by a provider method
 *
 * @param identifierName The name of this binding logic. Should be globally unique.
 * @param boundType The type which is bound
 * @param dependencies Other bindings this provider depends on
 * @param providingLogic The actual provision logic
 * @param scope The scope of the binding (RequestScoped, Singleton etc.). Empty if no scope
 * @param sourceFramework In case this binding is being generated by copying an existing 3rd party
 *     binding from a library, this value denotes the dependency injection framework of that
 *     binding.
 */
public record ProviderMethod(
    String identifierName,
    TypeName boundType,
    List<ParameterSpec> dependencies,
    CodeBlock providingLogic,
    List<AnnotationSpec> annotations,
    BindingScope scope,
    DepInjectionFramework sourceFramework)
    implements Binding {

  public ProviderMethod(
      String identifierName,
      TypeName boundType,
      List<ParameterSpec> dependencies,
      CodeBlock providingLogic,
      BindingScope scope) {
    this(identifierName, boundType, dependencies, providingLogic, List.of(), scope, NONE);
  }
}
