systemProp.org.gradle.internal.publish.checksums.insecure=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx2g
#org.gradle.configuration-cache=true

com.flipkart.krystal.previousVersion=11.3.2
com.flipkart.krystal.currentVersion=11.3.3
com.flipkart.krystal.lattice.currentVersion=0.6.3
java_code_std_version=6.0
# This project property is consumed by the "com.flipkart.java.code.standard" Gradle plugin
#
# Change this to "false" to find code issues reported by checkerFramework, error-prone etc.
#
# Temporarily defaulting to unsafe compilation since there is a bug in checkerFramework
# which causes failure when compiling DefaultFacetSpec class with this error:
# "class file for org.checkerframework.checker.nonempty.qual.UnknownNonEmpty not found"
unsafeCompile=true
