package com.flipkart.krystal.vajram.ext.sql.vertx;

import static com.flipkart.krystal.model.IfAbsent.IfAbsentThen.FAIL;

import com.flipkart.krystal.model.IfAbsent;
import com.flipkart.krystal.vajram.IOVajramDef;
import com.flipkart.krystal.vajram.Vajram;
import com.flipkart.krystal.vajram.facets.Output;
import io.vertx.sqlclient.Pool;
import io.vertx.sqlclient.Row;
import io.vertx.sqlclient.RowSet;
import io.vertx.sqlclient.Tuple;
import java.util.concurrent.CompletableFuture;

/**
 * IO Vajram that executes a parameterized SQL query using the Vert.x SQL client.
 *
 * <p>This vajram is intended to be called by Compute Vajrams generated by {@code
 * vajram-sql-vertx-codegen}. It accepts a prepared SQL statement, its parameters, and a Vert.x
 * connection pool, and returns the raw {@link RowSet} for the caller to map to domain objects.
 *
 * <p>The query is executed as a prepared statement to prevent SQL injection.
 */
@Vajram
@SuppressWarnings("initialization.field.uninitialized")
public abstract class ExecuteVertxSql extends IOVajramDef<RowSet<Row>> {

  interface _Inputs {
    /** Parameterized SQL SELECT statement with positional placeholders. */
    @IfAbsent(FAIL)
    String sql();

    /** Positional parameter values matching the placeholders in {@link #sql()}. */
    @IfAbsent(FAIL)
    Tuple params();

    /** Vert.x connection pool used to execute the query. */
    @IfAbsent(FAIL)
    Pool pool();
  }

  @Output
  static CompletableFuture<RowSet<Row>> execute(String sql, Tuple params, Pool pool) {
    return pool.preparedQuery(sql).execute(params).toCompletionStage().toCompletableFuture();
  }
}
