package com.flipkart.krystal.caramel.samples.basic.classification;

import com.flipkart.krystal.caramel.model.AccessBeforeInitializationException;
import com.flipkart.krystal.caramel.model.CaramelField;
import com.flipkart.krystal.caramel.model.SimpleCaramelField;
import com.flipkart.krystal.caramel.model.Value;
import com.flipkart.krystal.caramel.model.ValueImpl;
import com.flipkart.krystal.caramel.samples.basic.TransformedProduct;
import org.checkerframework.checker.initialization.qual.NotOnlyInitialized;

// Auto Generated by Caramel
public class TransformedProductPayload implements TransformedProductPayloadDefinition {

  public TransformedProductPayload() {
    finalTransformedProduct =
        new ValueImpl<>(TransformedProductPayloadFields.finalTransformedProduct, this);
    x2String = new ValueImpl<>(TransformedProductPayloadFields.x2String, this);
    initialTransformedProduct =
        new ValueImpl<>(TransformedProductPayloadFields.initialTransformedProduct, this);
  }

  interface TransformedProductPayloadFields {

    CaramelField<TransformedProduct, TransformedProductPayload> initialTransformedProduct =
        new SimpleCaramelField<>(
            "initialTransformedProduct",
            TransformedProductPayload.class,
            TransformedProductPayload::getInitialTransformedProduct,
            TransformedProductPayload::setInitialTransformedProduct);

    CaramelField<String, TransformedProductPayload> x2String =
        new SimpleCaramelField<>(
            "x2String",
            TransformedProductPayload.class,
            TransformedProductPayload::getX2String,
            TransformedProductPayload::setX2String);

    CaramelField<TransformedProduct, TransformedProductPayload> finalTransformedProduct =
        new SimpleCaramelField<>(
            "finalTransformedProduct",
            TransformedProductPayload.class,
            TransformedProductPayload::getFinalTransformedProduct,
            TransformedProductPayload::setFinalTransformedProduct);
  }

  @NotOnlyInitialized
  private final Value<TransformedProduct, TransformedProductPayload> initialTransformedProduct;

  @NotOnlyInitialized private final Value<String, TransformedProductPayload> x2String;

  @NotOnlyInitialized
  private final Value<TransformedProduct, TransformedProductPayload> finalTransformedProduct;

  @Override
  public TransformedProduct getInitialTransformedProduct() {
    return initialTransformedProduct
        .get()
        .orElseThrow(() -> new AccessBeforeInitializationException(initialTransformedProduct));
  }

  public void setInitialTransformedProduct(TransformedProduct transformedProduct) {
    initialTransformedProduct.set(transformedProduct);
  }

  @Override
  public String getX2String() {
    return x2String.get().orElseThrow(() -> new AccessBeforeInitializationException(x2String));
  }

  public void setX2String(String string) {
    x2String.set(string);
  }

  @Override
  public TransformedProduct getFinalTransformedProduct() {
    return finalTransformedProduct
        .get()
        .orElseThrow(() -> new AccessBeforeInitializationException(finalTransformedProduct));
  }

  public void setFinalTransformedProduct(TransformedProduct transformedProduct) {}
}
