// Generated by vajram-lang-rust-compiler from helloWorld.vajram
#![allow(unused)]
use crate::vajram_rt::{Errable, VajramError};
use std::rc::Rc;

pub mod hello_world {
    use super::*;

    #[derive(Debug, Clone)]
    pub struct HelloWorldInputs {}

    pub struct HelloWorldDeps {
        pub writer: Rc<ConsoleWriter>,
    }

    pub fn call(inputs: HelloWorldInputs, deps: Rc<HelloWorldDeps>) -> Rc<()> {
        Rc::new(deps.writer.println("Hello! World.".to_string()))
    }
}
