// Generated by vajram-lang-rust-compiler from helloWorld.vajram
#![allow(unused)]
use crate::vajram_rt::{Errable, VajramError};
use std::rc::Rc;

pub mod hello_world {
    use super::*;

    #[derive(Debug, Clone)]
    pub struct HelloWorldInputs {}

    pub struct HelloWorldDeps {
        pub writer: Rc<ConsoleWriter>,
    }

    pub fn call(inputs: Vec<HelloWorldInputs>, deps: Rc<HelloWorldDeps>) -> Vec<Rc<()>> {
        inputs
            .into_iter()
            .map(|inputs| call_one(inputs, Rc::clone(&deps)))
            .collect()
    }

    fn call_one(inputs: HelloWorldInputs, deps: Rc<HelloWorldDeps>) -> Rc<()> {
        Rc::new(deps.writer.println("Hello! World.".to_string()))
    }
}
