package com.flipkart.krystal.caramel.samples.basic;

import com.flipkart.krystal.caramel.model.AbstractValue;
import com.flipkart.krystal.caramel.model.AccessBeforeInitializationException;
import com.flipkart.krystal.caramel.model.Field;
import com.flipkart.krystal.caramel.model.SimpleField;
import java.util.Collection;
import java.util.List;

// AutoGenerated and managed by Caramel
public final class TestPayload implements TestPayloadDefinition {

  interface TestPayloadFields {

    Field<String, TestPayload> x1String =
        new SimpleField<>(
            "x1String", TestPayload.class, TestPayload::x1String, TestPayload::setX1String);
    Field<ProductUpdateEventsContainer, TestPayload> productUpdateEvents =
        new SimpleField<>(
            "productUpdateEvents",
            TestPayload.class,
            TestPayload::productUpdateEvents,
            TestPayload::setProductUpdateEvents);
    Field<TransformedProduct, TestPayload> initialTransformedProduct =
        new SimpleField<>(
            "initialTransformedProduct",
            TestPayload.class,
            TestPayload::initialTransformedProduct,
            TestPayload::setInitialTransformedProduct);
    Field<ProductUpdateEvent, TestPayload> initProductEvent =
        new SimpleField<>(
            "initProductEvent",
            TestPayload.class,
            TestPayload::initProductEvent,
            TestPayload::setInitProductEvent);
    Field<List<TransformedProduct>, TestPayload> conditionalTransformedProducts =
        new SimpleField<>(
            "conditionalTransformedProducts",
            TestPayload.class,
            TestPayload::conditionalTransformedProducts,
            TestPayload::setConditionalTransformedProducts);
    Field<String, TestPayload> triggerUserId =
        new SimpleField<>(
            "triggerUserId",
            TestPayload.class,
            TestPayload::triggerUserId,
            TestPayload::setTriggerUserId);

    Field<Collection<Metric>, TestPayload> metrics =
        new SimpleField<>(
            "metrics", TestPayload.class, TestPayload::metrics, TestPayload::setMetrics);

    Field<Boolean, TestPayload> isEnableValidation =
        new SimpleField<>(
            "isEnableValidation",
            TestPayload.class,
            TestPayload::isEnableValidation,
            TestPayload::setIsEnableValidation);
    Field<String, TestPayload> string =
        new SimpleField<>("string", TestPayload.class, TestPayload::string, TestPayload::setString);

    Field<String, TestPayload> secondString =
        new SimpleField<>(
            "secondString",
            TestPayload.class,
            TestPayload::secondString,
            TestPayload::setSecondString);
    Field<TransformedProduct, TestPayload> nextProduct =
        new SimpleField<>(
            "nextProduct",
            TestPayload.class,
            TestPayload::nextProduct,
            TestPayload::setNextProduct);
  }

  private final Value<String> x1String = new Value<>(TestPayloadFields.x1String);
  private final Value<ProductUpdateEventsContainer> productUpdateEvents =
      new Value<>(TestPayloadFields.productUpdateEvents);
  private final Value<TransformedProduct> initialTransformedProduct =
      new Value<>(TestPayloadFields.initialTransformedProduct);
  private final Value<ProductUpdateEvent> initProductEvent =
      new Value<>(TestPayloadFields.initProductEvent);
  private final Value<List<TransformedProduct>> conditionalTransformedProducts =
      new Value<>(TestPayloadFields.conditionalTransformedProducts);
  private final Value<String> triggerUserId = new Value<>(TestPayloadFields.triggerUserId);
  private final Value<Collection<Metric>> metrics = new Value<>(TestPayloadFields.metrics);
  private final Value<Boolean> isEnableValidation =
      new Value<>(TestPayloadFields.isEnableValidation);
  private final Value<String> string = new Value<>(TestPayloadFields.string);
  private final Value<String> secondString = new Value<>(TestPayloadFields.secondString);
  private final Value<TransformedProduct> nextProduct = new Value<>(TestPayloadFields.nextProduct);

  public String x1String() {
    return x1String.get().orElseThrow();
  }

  public void setX1String(String string) {
    x1String.set(string);
  }

  @Override
  public ProductUpdateEventsContainer productUpdateEvents() {
    return productUpdateEvents.get().orElseThrow();
  }

  public void setProductUpdateEvents(ProductUpdateEventsContainer productUpdateEvents) {
    this.productUpdateEvents.set(productUpdateEvents);
  }

  @Override
  public TransformedProduct initialTransformedProduct() {
    return initialTransformedProduct.get().orElseThrow();
  }

  public void setInitialTransformedProduct(TransformedProduct transformedProduct) {
    this.initialTransformedProduct.set(transformedProduct);
  }

  @Override
  public ProductUpdateEvent initProductEvent() {
    return initProductEvent.get().orElseThrow();
  }

  public void setInitProductEvent(ProductUpdateEvent productEvent) {
    this.initProductEvent.set(productEvent);
  }

  public List<TransformedProduct> conditionalTransformedProducts() {
    return conditionalTransformedProducts.get().orElseThrow();
  }

  public void setConditionalTransformedProducts(List<TransformedProduct> transformedProducts) {
    this.conditionalTransformedProducts.set(transformedProducts);
  }

  @Override
  public String triggerUserId() {
    return triggerUserId
        .get()
        .orElseThrow(() -> new AccessBeforeInitializationException(triggerUserId));
  }

  public void setTriggerUserId(String triggerUserId) {
    this.triggerUserId.set(triggerUserId);
  }

  @Override
  public Collection<Metric> metrics() {
    return metrics.getOrThrow();
  }

  public void setMetrics(Collection<Metric> metrics) {
    this.metrics.set(metrics);
  }

  @Override
  public boolean isEnableValidation() {
    return isEnableValidation.getOrThrow();
  }

  public void setIsEnableValidation(boolean isEnableValidation) {
    this.isEnableValidation.set(isEnableValidation);
  }

  @Override
  public String string() {
    return string.getOrThrow();
  }

  public void setString(String s) {
    string.set(s);
  }

  @Override
  public String secondString() {
    return secondString.getOrThrow();
  }

  public void setSecondString(String s) {
    secondString.set(s);
  }

  @Override
  public TransformedProduct nextProduct() {
    return nextProduct.getOrThrow();
  }

  public void setNextProduct(TransformedProduct transformedProduct) {
    this.nextProduct.set(transformedProduct);
  }

  private final class Value<T> extends AbstractValue<T, TestPayload> {

    private final Field<T, TestPayload> field;

    public Value(Field<T, TestPayload> field) {
      this.field = field;
    }

    @Override
    public Field<T, TestPayload> field() {
      return field;
    }

    @Override
    public TestPayload getPayload() {
      return TestPayload.this;
    }
  }
}
