package com.flipkart.krystal.caramel.samples.basic;

import com.flipkart.krystal.caramel.model.AbstractValue;
import com.flipkart.krystal.caramel.model.AccessBeforeInitializationException;
import com.flipkart.krystal.caramel.model.Field;
import com.flipkart.krystal.caramel.model.SimpleField;

// Auto Generated by Caramel
public class TransformedProductPayload
    implements TransformedProductPayloadDefinition {

  interface TransformedProductPayloadFields {

    Field<TransformedProduct, TransformedProductPayload> initialTransformedProduct =
        new SimpleField<>(
            "initialTransformedProduct",
            TransformedProductPayload.class,
            TransformedProductPayload::getInitialTransformedProduct,
            TransformedProductPayload::setInitialTransformedProduct);

    Field<String, TransformedProductPayload> x2String =
        new SimpleField<>(
            "x2String",
            TransformedProductPayload.class,
            TransformedProductPayload::getX2String,
            TransformedProductPayload::setX2String);

    Field<TransformedProduct, TransformedProductPayload> finalTransformedProduct =
        new SimpleField<>(
            "finalTransformedProduct",
            TransformedProductPayload.class,
            TransformedProductPayload::getFinalTransformedProduct,
            TransformedProductPayload::setFinalTransformedProduct);
  }

  private final Value<TransformedProduct> initialTransformedProduct =
      new Value<>(TransformedProductPayloadFields.initialTransformedProduct);
  private final Value<String> x2String = new Value<>(TransformedProductPayloadFields.x2String);
  private final Value<TransformedProduct> finalTransformedProduct =
      new Value<>(TransformedProductPayloadFields.finalTransformedProduct);

  @Override
  public TransformedProduct getInitialTransformedProduct() {
    return initialTransformedProduct
        .get()
        .orElseThrow(() -> new AccessBeforeInitializationException(initialTransformedProduct));
  }

  public void setInitialTransformedProduct(TransformedProduct transformedProduct) {
    initialTransformedProduct.set(transformedProduct);
  }

  @Override
  public String getX2String() {
    return x2String.get().orElseThrow(() -> new AccessBeforeInitializationException(x2String));
  }

  public void setX2String(String string) {
    x2String.set(string);
  }

  @Override
  public TransformedProduct getFinalTransformedProduct() {
    return finalTransformedProduct
        .get()
        .orElseThrow(() -> new AccessBeforeInitializationException(finalTransformedProduct));
  }

  public void setFinalTransformedProduct(TransformedProduct transformedProduct) {}

  private final class Value<T> extends AbstractValue<T, TransformedProductPayload> {

    private final Field<T, TransformedProductPayload> field;

    public Value(Field<T, TransformedProductPayload> field) {
      this.field = field;
    }

    @Override
    public Field<T, TransformedProductPayload> field() {
      return field;
    }

    @Override
    public TransformedProductPayload getPayload() {
      return TransformedProductPayload.this;
    }
  }
}
