plugins {
    id 'org.kordamp.gradle.jandex' version "${kordamp_jandex_version}"
}

description = "Core module for Lattice - Provides the core functionality for Lattice Apps"

dependencies {
    api project(':krystex')
    implementation project(':krystal-common')

    implementation libs.jackson.annotations
    implementation libs.jackson.databind
    implementation libs.jackson.dataformat.yaml
    implementation libs.jackson.datatype.guava

    implementation 'jakarta.enterprise:jakarta.enterprise.cdi-api'
    implementation 'commons-cli:commons-cli'
}
