[versions]
lombok = '1.18.46'
jackson = '2.21.4'
protobuf = '4.36.0'
slf4j = '2.0.18'
guice = '7.0.0'
grpc = '1.83.1'
mockito = '5.23.0'
assertj = '3.27.7'
resilience4j = '2.4.0'

quarkus = '3.33.3.1' #LTS Note:3.33.3.2 needs to updated soon
# This is the version of vertx compatible with the above version of quarkus. Upgrade only in sync with quarkus version
# Source: https://github.com/quarkusio/quarkus-platform/blob/3.37/generated-platform-project/quarkus/bom/pom.xml
# As can be seen in the above file, all vertx dependencies (<groupId>io.vertx</groupId>) have been pinned to the following version
vertx = '4.5.31'

[libraries]
vertx-stack-depchain = { module = 'io.vertx:vertx-stack-depchain', version.ref = 'vertx' }
quarkus-bom = { module = 'io.quarkus.platform:quarkus-bom', version.ref = 'quarkus' }
jackson-bom = {module = 'com.fasterxml.jackson:jackson-bom', version.ref = 'jackson'}
protobuf-bom = {module = 'com.google.protobuf:protobuf-bom', version.ref = 'protobuf'}
slf4j-bom = {module = 'org.slf4j:slf4j-bom', version.ref = 'slf4j'}
guice-bom = {module = 'com.google.inject:guice-bom', version.ref = 'guice'}
grpc-bom = {module = 'io.grpc:grpc-bom', version.ref = 'grpc'}
resilience4j-bom = {module = 'io.github.resilience4j:resilience4j-bom', version.ref = 'resilience4j'}
mockito-bom = {module = 'org.mockito:mockito-bom', version.ref = 'mockito'}
assertj-bom = {module = 'org.assertj:assertj-bom', version.ref = 'assertj'}

lombok = { module = 'org.projectlombok:lombok', version.ref = 'lombok' }

scram-client = { module = 'com.ongres.scram:scram-client' }