package com.flipkart.krystal.caramel.samples.basic.stringconversion;

import static com.flipkart.krystal.caramel.samples.basic.stringconversion.StringConversionPayload.StringConversionFields.input;
import static com.flipkart.krystal.caramel.samples.basic.stringconversion.StringConversionPayload.StringConversionFields.output;

import com.flipkart.krystal.caramel.model.Field;
import com.flipkart.krystal.caramel.model.SimpleField;
import com.flipkart.krystal.caramel.model.Value;
import com.flipkart.krystal.caramel.model.ValueImpl;

// AutoGenerated and managed by Caramel
class StringConversionPayload implements StringConversionPayloadDefinition {
  interface StringConversionFields {
    Field<Object, StringConversionPayload> input =
        new SimpleField<>(
            "input",
            StringConversionPayload.class,
            StringConversionPayload::input,
            StringConversionPayload::setInput);

    Field<String, StringConversionPayload> output =
        new SimpleField<>(
            "output",
            StringConversionPayload.class,
            StringConversionPayload::output,
            StringConversionPayload::setOutput);
  }

  private final Value<Object, StringConversionPayload> _input = new ValueImpl<>(input, this);
  private final Value<String, StringConversionPayload> _output = new ValueImpl<>(output, this);

  @Override
  public Object input() {
    return _input.getOrThrow();
  }

  public void setInput(Object value) {
    _input.set(value);
  }

  @Override
  public String output() {
    return _output.getOrThrow();
  }

  public void setOutput(String string) {
    _output.set(string);
  }
}
