package com.flipkart.krystal.vajram.ext.sql.statement;

import static java.lang.annotation.ElementType.TYPE;

import java.lang.annotation.Target;

/**
 * Marks a trait as an SQL trait - implying that a Vajram containing an SQL statement and
 * implementing the SQL trait will be generated by the framework.
 */
@Target(TYPE)
public @interface SQL {}
