// Generated by vajram-lang-rust-compiler from computeAveragePrice.vajram
#![allow(unused)]
use crate::vajram_rt::{Errable, VajramError};
use std::rc::Rc;

pub mod compute_average_price {
    use super::*;

    #[derive(Debug, Clone)]
    pub struct ComputeAveragePriceInputs {
        pub collection: Rc<ProductCollection>,
    }

    pub async fn call(inputs: Vec<ComputeAveragePriceInputs>) -> Result<Vec<Rc<f64>>, VajramError> {
        futures::future::try_join_all(inputs.into_iter().map(|inputs| call_one(inputs))).await?
    }

    async fn call_one(inputs: ComputeAveragePriceInputs) -> Result<Rc<f64>, VajramError> {
        let _productDetails_inputs = inputs.clone();
        let productDetails = crate::vajram_rt::spawn_local_shared(async move {
            crate::com::flipkart::krystal::vajram_lang::samples::products::get_product_details::get_product_details::call(_productDetails_inputs.collection.productIds().into_iter().map(|it| crate::com::flipkart::krystal::vajram_lang::samples::products::get_product_details::get_product_details::GetProductDetailsInputs { productId: Rc::new(it) }).collect()).await
        });
        Rc::new(
            productDetails
                .clone()
                .await
                .values()
                .stream()
                .filter(it.valuePresent())
                .map(it.price())
                .mapToDouble()
                .average(),
        )
    }
}
