// Generated by vajram-lang-rust-compiler from getAvailableProductDetails.vajram
#![allow(unused)]
use crate::vajram_rt::{Errable, VajramError};
use std::rc::Rc;

#[derive(Debug, Clone)]
pub struct GetAvailableProductDetailsInputs {
    pub productId: Rc<String>,
}

pub async fn call(
    inputs: GetAvailableProductDetailsInputs,
) -> Result<Rc<ProductDetails>, VajramError> {
    let _isAvailable_inputs = inputs.clone();
    let isAvailable = crate::vajram_rt::spawn_local_shared(async move {
        crate::com::flipkart::krystal::vajram_lang::samples::products::is_product_available::call(crate::com::flipkart::krystal::vajram_lang::samples::products::is_product_available::IsProductAvailableInputs { productId: Rc::clone(&_isAvailable_inputs.productId) }).await
    });
    // NOTE: ignoring `skipIf` clause - not modeled by this compiler yet
    return crate::com::flipkart::krystal::vajram_lang::samples::products::get_product_details::call(crate::com::flipkart::krystal::vajram_lang::samples::products::get_product_details::GetProductDetailsInputs { productId: Rc::clone(&inputs.productId) }).await.default(|it| { ProductDetails::new(inputs.productId) });
}
