// Generated by vajram-lang-rust-compiler from getAvailableProductDetails.vajram
#![allow(unused)]
use crate::vajram_rt::{Errable, VajramError};
use std::rc::Rc;

pub mod get_available_product_details {
    use super::*;

    #[derive(Debug, Clone)]
    pub struct GetAvailableProductDetailsInputs {
        pub productId: Rc<String>,
    }

    pub async fn call(
        inputs: Vec<GetAvailableProductDetailsInputs>,
    ) -> Result<Vec<Rc<ProductDetails>>, VajramError> {
        futures::future::try_join_all(inputs.into_iter().map(|inputs| call_one(inputs))).await?
    }

    async fn call_one(
        inputs: GetAvailableProductDetailsInputs,
    ) -> Result<Rc<ProductDetails>, VajramError> {
        let _isAvailable_inputs = inputs.clone();
        let isAvailable = crate::vajram_rt::spawn_local_shared(async move {
            (crate::com::flipkart::krystal::vajram_lang::samples::products::is_product_available::is_product_available::call(vec![crate::com::flipkart::krystal::vajram_lang::samples::products::is_product_available::is_product_available::IsProductAvailableInputs { productId: Rc::clone(&_isAvailable_inputs.productId) }]).await).into_iter().next().expect("single-item Vajram batch")
        });
        // NOTE: ignoring `skipIf` clause - not modeled by this compiler yet
        return (crate::com::flipkart::krystal::vajram_lang::samples::products::get_product_details::get_product_details::call(vec![crate::com::flipkart::krystal::vajram_lang::samples::products::get_product_details::get_product_details::GetProductDetailsInputs { productId: Rc::clone(&inputs.productId) }]).await).into_iter().next().expect("single-item Vajram batch").default(|it| { ProductDetails::new(inputs.productId) });
    }
}
