// Generated by vajram-lang-rust-compiler from getProductDetails.vajram
#![allow(unused)]
use crate::vajram_rt::{Errable, VajramError};
use std::rc::Rc;

pub mod get_product_details {
    use super::*;

    #[derive(Debug, Clone)]
    pub struct GetProductDetailsInputs {
        pub productId: Rc<String>,
    }

    pub struct GetProductDetailsDeps {
        pub productDB: Rc<ProductDB>,
    }

    pub async fn call(
        inputs: Vec<GetProductDetailsInputs>,
        deps: Rc<GetProductDetailsDeps>,
    ) -> Result<Vec<Rc<ProductDetails>>, VajramError> {
        futures::future::try_join_all(
            inputs
                .into_iter()
                .map(|inputs| call_one(inputs, Rc::clone(&deps))),
        )
        .await?
    }

    async fn call_one(
        inputs: GetProductDetailsInputs,
        deps: Rc<GetProductDetailsDeps>,
    ) -> Result<Rc<ProductDetails>, VajramError> {
        let productIds = batch_key.batches().map(|it| it.productId()).toList();
        let productDetails = deps
            .productDB
            .getProductDetails(productIds)
            .await
            .stream()
            .await
            .toMap(BatchKey::new(it.productId()), it);
        Rc::clone(&productDetails)
    }
}
