// Generated by vajram-lang-rust-compiler from isProductAvailable.vajram
#![allow(unused)]
use crate::vajram_rt::{Errable, VajramError};
use std::rc::Rc;

pub mod is_product_available {
    use super::*;

    #[derive(Debug, Clone)]
    pub struct IsProductAvailableInputs {
        pub productId: Rc<String>,
    }

    pub struct IsProductAvailableDeps {
        pub availabilityDB: Rc<AvailabilityDB>,
    }

    pub async fn call(
        inputs: Vec<IsProductAvailableInputs>,
        deps: Rc<IsProductAvailableDeps>,
    ) -> Result<Vec<Rc<bool>>, VajramError> {
        futures::future::try_join_all(
            inputs
                .into_iter()
                .map(|inputs| call_one(inputs, Rc::clone(&deps))),
        )
        .await?
    }

    async fn call_one(
        inputs: IsProductAvailableInputs,
        deps: Rc<IsProductAvailableDeps>,
    ) -> Result<Rc<bool>, VajramError> {
        Rc::new(deps.availabilityDB.isAvailable(inputs.productId))
    }
}
