// Generated by vajram-lang-rust-compiler from isProductAvailable.vajram
#![allow(unused)]
use crate::vajram_rt::{Errable, VajramError};
use std::rc::Rc;

pub mod is_product_available {
    use super::*;

    #[derive(Debug, Clone)]
    pub struct IsProductAvailableInputs {
        pub productId: Rc<String>,
    }

    pub struct IsProductAvailable_Injections {
        pub availabilityDB: Rc<dyn crate::vajram_rt::Provider<AvailabilityDB>>,
    }
    impl IsProductAvailable_Injections {
        fn new<I: crate::vajram_rt::Injector + 'static>(
            context: Rc<crate::vajram_rt::AppContext<I>>,
        ) -> Rc<Self> {
            Rc::new(Self {
                availabilityDB: context.injector().get_provider(
                    crate::vajram_rt::InjectionKey::new(
                        "com.flipkart.krystal.vajram_lang.samples.products.AvailabilityDB",
                        &[],
                    ),
                    Rc::clone(&context),
                ),
            })
        }
        fn instance<I: crate::vajram_rt::Injector + 'static>(
            context: Rc<crate::vajram_rt::AppContext<I>>,
        ) -> Rc<Self> {
            context.injection_instance("IsProductAvailable_Injections", || {
                Self::new(Rc::clone(&context))
            })
        }
    }

    pub async fn call<I: crate::vajram_rt::Injector + 'static>(
        inputs: Vec<IsProductAvailableInputs>,
        context: Rc<crate::vajram_rt::AppContext<I>>,
    ) -> Result<Vec<Rc<bool>>, VajramError> {
        let deps = IsProductAvailable_Injections::instance(Rc::clone(&context));
        futures::future::try_join_all(
            inputs
                .into_iter()
                .map(|inputs| call_one(inputs, Rc::clone(&deps), Rc::clone(&context))),
        )
        .await?
    }

    async fn call_one<I: crate::vajram_rt::Injector + 'static>(
        inputs: IsProductAvailableInputs,
        deps: Rc<IsProductAvailable_Injections>,
        context: Rc<crate::vajram_rt::AppContext<I>>,
    ) -> Result<Rc<bool>, VajramError> {
        Rc::new(deps.availabilityDB.get().isAvailable(inputs.productId))
    }
}
