// Generated by vajram-lang-rust-compiler from isProductAvailable.vajram
#![allow(unused)]
use crate::vajram_rt::{Errable, VajramError};
use std::rc::Rc;

#[derive(Debug, Clone)]
pub struct IsProductAvailableInputs {
    pub productId: Rc<String>,
}

pub struct IsProductAvailableDeps {
    pub availabilityDB: Rc<AvailabilityDB>,
}

pub async fn call(
    inputs: IsProductAvailableInputs,
    deps: Rc<IsProductAvailableDeps>,
) -> Result<Rc<bool>, VajramError> {
    Rc::new(deps.availabilityDB.isAvailable(inputs.productId))
}
