"""

"""
directive @entity on OBJECT

"""
Marks a field as part of the id of its containing GraphQL type.

Invariants:
Id fields cannot accept arguments
Id fields have to be scalars - cannot be graphql objects
"""
directive @idField on FIELD_DEFINITION

"""
Specifies the vajram responsible for fetching data for one or more fields of a GraphQL type.
By default, its response is assigned directly to the annotated field. Set multiField to true
when the vajram returns an aggregate response: each field using the same vajramId receives the
value from the correspondingly named field in that response. multiField defaults to false.
Data fetchers can be used only for Scalar types. Using them on fields of type
object throws an error.

Invariants:
@dataFetchers can only be used on scalar types. Using on object types throws build-time error.
"""
#TODO: Validation: Throw error if used with object types
directive @dataFetcher(vajramId : String!, subPackage: String, multiField: Boolean = false) on FIELD_DEFINITION

"""
Specifies the vajram which is responsible for fetching the identity of a GraphQL object.
This is useful when a field depicts a one-to-one or one-to-many relationship between GraphQL objects.
For example, if an entity of type Book has a field "author" of type Author, an @idFetcher vajram returns Author_Id.
"""
#TODO: TEst case: Should support fanout and one2one
directive @idFetcher(vajramId : String!, subPackage: String) on FIELD_DEFINITION


"""
This means the identity used for type aggregation should be taken from the arguments passed to the field
by matching the argument name with the idField name. If any of the non-null idFields of the type doesn't have a
corresponding field argument with matching name and type, then a build-time error is thrown

Invariants:
Only valid on fields of root operation types.
Every non-null idField of the type must have a corresponding field argument here with matching name and type
"""
#TODO Validation: inferIdFromArgs can only be present in fields inside root operation types
directive @inferIdFromArgs on FIELD_DEFINITION

"""
Specifies that the id fields of the parent entity should be used to aggregate the given field.
Using this directive on a field is only valid if the field type is an Object type
with the directive @entityExtension whose "ofEntity" argument matches the composing entity type

Invariants:
Can only be used on a field whose type has @entityExtension with "ofEntity" arg matching the parent type of this field - else build-time error is thrown
The field cannot be a list field - else build-time error is thrown
Only one field of the the "extended" type can have this type - having more than one is a build-time error.
"""
#TODO: Validation: throw error if used in non-@entityExtension
#TODO: Validation: throw error if used with lists (fanout should not be supported)
directive @inferIdFromParent on FIELD_DEFINITION

"""
Specifies the Java type mapping for a GraphQL scalar type.

Example:
scalar Timestamp
@specifiedBy(url: "https://scalars.graphql.org/andimarek/date-time.html")
@javaType(packageName: "java.time", className: "OffsetDateTime")

type Order {
createdAt: Timestamp    # Will be mapped to java.time.OffsetDateTime
}
"""
directive @javaType(packageName : String!, className: String!) on SCALAR

"""
Specifies the root package under which all data fetchers and id fetchers vajrams are located.
If a vajram is located in a subpackage inside the root package,
the sub package suffix can be specified separately in the @dataFetcher and @idFetcher directives.
"""
directive @rootPackage(name: String!) on SCHEMA

"""
Specifies the sub package inside @rootPackage under which all the models corresponding to an object are to be generated
"""
directive @subPackage(name: String!) on OBJECT

"""
Specifies that a given type is an "extension" of some entity. This means the "extension"
entity organizes some fields of the "extended" entity into a new type for better field organization.
This implies that any @dataFetchers or @idFetchers on the fields of an extension type must accept
the extended entity's `<Entity>_Id` and compute the values of the fields based on it.

Note: an instance of an entity extension has a one-to-one correspondence with an instance of the extended entity.
i.e. An entity can have exactly one field of type EntityExtension and that field cannot have any arguments, nor can it be a array field.
This implies that an entity extension can be used in very limited circumstances, for ex: an entity has many fields
and we want to organize the fields into smaller types which "extend" that entity and group some of its fields into a different type.
"""
#TODO: Validation: Can be used only on @entity fields and @entityExtension fields.
#TODO: Validation: When used in @entityExtensions, the "ofEntity" must match the outer "ofEntity"
directive @entityExtension(ofEntity: String!) on OBJECT
