// Generated by vajram-lang-rust-compiler from getUserInfo.vajram
#![allow(unused)]
use crate::vajram_rt::{Errable, VajramError};
use std::rc::Rc;

#[derive(Debug, Clone)]
pub struct GetUserInfoInputs {
    pub userId: Rc<String>,
}

pub struct GetUserInfoDeps {
    pub svcClient: Rc<UserServiceClient>,
}

pub async fn call(inputs: GetUserInfoInputs, deps: Rc<GetUserInfoDeps>) -> Rc<UserInfo> {
    Rc::clone(&inputs.userId)
}
