// Generated by vajram-lang-rust-compiler from sayHelloToFriends.vajram
#![allow(unused)]
use crate::vajram_rt::{Errable, VajramError};
use std::rc::Rc;

pub mod say_hello_to_friends {
    use super::*;

    #[derive(Debug, Clone)]
    pub struct SayHelloToFriendsInputs {
        pub userId: Rc<String>,
        pub numberOfFriends: Rc<Result<i64, VajramError>>,
    }

    pub async fn call(inputs: SayHelloToFriendsInputs) -> Rc<String> {
        let _userInfo_inputs = inputs.clone();
        let userInfo = crate::vajram_rt::spawn_local_shared(async move {
            crate::com::flipkart::krystal::vajram_lang::samples::friends::get_user_info::get_user_info::call(crate::com::flipkart::krystal::vajram_lang::samples::friends::get_user_info::get_user_info::GetUserInfoInputs { userId: Rc::clone(&_userInfo_inputs.userId) }).await
        });
        let _friendsInfos_inputs = inputs.clone();
        let friendsInfos = crate::vajram_rt::spawn_local_shared(async move {
            futures::future::join_all(IntStream.range(0, _friendsInfos_inputs.numberOfFriends.default(2)).mapToObj(i, getFriendId(i)).into_iter().map(|it| async move { crate::com::flipkart::krystal::vajram_lang::samples::friends::get_user_info::get_user_info::call(crate::com::flipkart::krystal::vajram_lang::samples::friends::get_user_info::get_user_info::GetUserInfoInputs { userId: Rc::new(it) }).await })).await
        });
        Rc::new(
            "Hello Friends of %s ! %s".to_string().formatted(
                userInfo.clone().await.name(),
                friendInfos
                    .responses()
                    .filterPresent()
                    .map(|it| it.userName())
                    .collect(joining(", ".to_string())),
            ),
        )
    }
}
