package com.flipkart.krystal.vajram.protobuf3.codegen;

import static com.flipkart.krystal.codegen.common.datatypes.StandardJavaType.BYTE;
import static com.flipkart.krystal.codegen.common.models.CodeGenUtility.ContainerType.LIST;
import static com.flipkart.krystal.codegen.common.models.CodeGenUtility.capitalizeFirstChar;
import static com.flipkart.krystal.vajram.protobuf3.Protobuf3.PROTOBUF_3;
import static com.flipkart.krystal.vajram.protobuf3.codegen.Proto3SchemaGen.validateModelType;
import static com.flipkart.krystal.vajram.protobuf3.codegen.ProtoGenUtils.isProtoTypeMap;
import static com.flipkart.krystal.vajram.protobuf3.codegen.ProtoGenUtils.isProtoTypeRepeated;
import static com.flipkart.krystal.vajram.protobuf3.codegen.VajramProtoConstants.MODELS_PROTO_MSG_SUFFIX;
import static com.squareup.javapoet.MethodSpec.methodBuilder;
import static java.util.Map.entry;
import static java.util.Map.ofEntries;
import static javax.lang.model.element.Modifier.FINAL;
import static javax.lang.model.element.Modifier.PRIVATE;
import static javax.lang.model.element.Modifier.PUBLIC;
import static javax.lang.model.element.Modifier.STATIC;

import com.flipkart.krystal.codegen.common.datatypes.CodeGenType;
import com.flipkart.krystal.codegen.common.models.CodeGenUtility;
import com.flipkart.krystal.codegen.common.models.CodeGenUtility.ContainerType;
import com.flipkart.krystal.codegen.common.models.CodeGenUtility.ModelRootInfo;
import com.flipkart.krystal.codegen.common.models.CodegenPhase;
import com.flipkart.krystal.codegen.common.models.DeclaredTypeVisitor;
import com.flipkart.krystal.codegen.common.spi.CodeGenerator;
import com.flipkart.krystal.codegen.common.spi.ModelsCodeGenContext;
import com.flipkart.krystal.model.IfAbsent.IfAbsentThen;
import com.flipkart.krystal.model.MandatoryFieldMissingException;
import com.flipkart.krystal.model.Model;
import com.flipkart.krystal.model.ModelRoot;
import com.flipkart.krystal.model.UnmodifiableModelList;
import com.flipkart.krystal.serial.SerializableModel;
import com.flipkart.krystal.vajram.protobuf3.ProtoListBuilder;
import com.flipkart.krystal.vajram.protobuf3.Protobuf3;
import com.flipkart.krystal.vajram.protobuf3.SerializableProtoModel;
import com.google.common.collect.Iterables;
import com.google.common.collect.Lists;
import com.google.protobuf.ByteString;
import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.ArrayTypeName;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.CodeBlock;
import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeName;
import com.squareup.javapoet.TypeSpec;
import com.squareup.javapoet.TypeSpec.Builder;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.TypeMirror;
import lombok.extern.slf4j.Slf4j;
import org.checkerframework.checker.nullness.qual.MonotonicNonNull;
import org.checkerframework.checker.nullness.qual.Nullable;

/**
 * This code generator generates implementations in the model root hierarchy. More specifically, it
 * generates a final class name "[ModelName]_ImmutProto" which extends the "[ModelName]_Immut"
 * interface and the {@link SerializableModel} interface. This class wraps the proto java model
 * generated by protoc, whose name is "[ModelName]_Proto". All the getters in the class delegate to
 * the proto model. It also contains a lazily initialized byte array field named
 * "_serializedPayload". This is initialized in a constructor which accepts a byte array. This also
 * generates an inner class inside the ImmutProto class which extends the
 * "[ModelName]_Immut.Builder" interface and wraps a "[ModelName]_Proto.Builder" instance and all
 * setter and getter calls are delegated to this.
 */
@Slf4j
public class Proto3ModelsGen implements CodeGenerator {

  private final ModelsCodeGenContext codeGenContext;
  private final CodeGenUtility util;

  public Proto3ModelsGen(ModelsCodeGenContext codeGenContext) {
    this.codeGenContext = codeGenContext;
    this.util = codeGenContext.util();
  }

  @Override
  public void generate() {
    if (!isApplicable()) {
      return;
    }
    validate();
    generateProtoImplementation();
  }

  private boolean isApplicable() {
    if (!CodegenPhase.FINAL.equals(codeGenContext.codegenPhase())) {
      util.note("Skipping protobuf models codegen since current phase is not FINAL");
      return false;
    }
    if (!isProto3SerdeSupported()) {
      util.note(
          "Skipping protobuf models codegen since Protobuf3 is not a supported protocol of the model "
              + codeGenContext.modelRootType());
      return false;
    }

    TypeElement modelRootType = codeGenContext.modelRootType();
    // Check if the model root has the ModelRoot annotation
    ModelRoot modelRootAnnotation = modelRootType.getAnnotation(ModelRoot.class);
    if (modelRootAnnotation == null) {
      util.note(
          "Skipping class '%s' since it doesn't have @ModelRoot annotation"
              .formatted(modelRootType.getQualifiedName()));
      return false;
    }

    return true;
  }

  /**
   * Checks if the model root supports Proto3 serialization.
   *
   * @return true if Proto3 is supported, false otherwise
   */
  private boolean isProto3SerdeSupported() {
    return util.typeExplicitlySupportsProtocol(codeGenContext.modelRootType(), Protobuf3.class);
  }

  private void validate() {
    TypeElement modelRootType = codeGenContext.modelRootType();
    validateModelType(modelRootType, util);
  }

  private void generateProtoImplementation() {
    TypeElement modelRootType = codeGenContext.modelRootType();
    ClassName immutClassName = util.getImmutInterfaceName(modelRootType);

    String protoClassName =
        util.getImmutClassName(codeGenContext.modelRootType(), PROTOBUF_3).simpleName();
    String packageName = immutClassName.packageName();

    // Generate the implementation class using JavaPoet
    TypeSpec typeSpec = generateImplementationTypeSpec(modelRootType, packageName, protoClassName);

    // Create JavaFile and write to source file
    JavaFile javaFile = JavaFile.builder(packageName, typeSpec).build();

    util.generateSourceFile(packageName + "." + protoClassName, javaFile.toString(), modelRootType);

    log.info("Generated protobuf implementation class: {}", protoClassName);
  }

  private TypeSpec generateImplementationTypeSpec(
      TypeElement modelRootType, String packageName, String protoClassName) {
    ClassName immutableProtoType = ClassName.get(packageName, protoClassName);
    ClassName immutInterfaceName = util.getImmutInterfaceName(modelRootType);
    ClassName immutModelName = immutInterfaceName;
    ClassName protoMsgType =
        ClassName.get(
            packageName, modelRootType.getSimpleName().toString() + MODELS_PROTO_MSG_SUFFIX);

    ClassName protoMsgOrBuilderType =
        ClassName.get(protoMsgType.packageName(), protoMsgType.simpleName() + "OrBuilder");

    // Extract model methods
    List<ExecutableElement> modelMethods = util.extractAndValidateModelMethods(modelRootType);

    // Create class interfaces
    TypeName serializableTypeName =
        ParameterizedTypeName.get(ClassName.get(SerializableProtoModel.class), protoMsgType);

    // Create field types
    TypeName byteArrayType = ArrayTypeName.of(TypeName.BYTE);

    // Create class builder
    Builder classBuilder =
        util.classBuilder(protoClassName, modelRootType.getQualifiedName().toString())
            .addModifiers(PUBLIC)
            .addSuperinterface(immutModelName)
            .addSuperinterface(serializableTypeName);

    // Add fields
    classBuilder.addField(
        FieldSpec.builder(
                byteArrayType.annotated(AnnotationSpec.builder(MonotonicNonNull.class).build()),
                "_serializedPayload",
                PRIVATE)
            .build());
    classBuilder.addField(
        FieldSpec.builder(
                protoMsgType.annotated(AnnotationSpec.builder(MonotonicNonNull.class).build()),
                "_proto",
                PRIVATE)
            .build());

    // Add constructor for serialized payload
    classBuilder.addMethod(
        MethodSpec.constructorBuilder()
            .addModifiers(PUBLIC)
            .addParameter(byteArrayType, "_serializedPayload")
            .addStatement("this._serializedPayload = _serializedPayload")
            .addStatement("this._proto = null")
            .build());

    // Add constructor for proto message
    classBuilder.addMethod(
        MethodSpec.constructorBuilder()
            .addModifiers(PUBLIC)
            .addParameter(protoMsgOrBuilderType, "_proto")
            .addCode(
"""
    this._proto =
        _proto instanceof $T _message
            ? _message
            : _proto instanceof $T.Builder _builder ? _builder.build() : /* Impossible */ null;
""",
                protoMsgType,
                protoMsgType)
            .addStatement("this._serializedPayload = null")
            .build());

    classBuilder.addMethod(copyCtor(modelMethods));

    // Add _serialize method from Serializable interface with lazy initialization
    classBuilder.addMethod(
        MethodSpec.overriding(util.getMethod(SerializableModel.class, "_serialize", 0))
            .addCode(
"""
if (_serializedPayload == null){
  this._serializedPayload = _proto.toByteArray();
}
return _serializedPayload;
""")
            .build());

    // Add _build method from ImmutableModel interface
    classBuilder.addMethod(
        methodBuilder("_build")
            .addAnnotation(Override.class)
            .addModifiers(PUBLIC)
            .returns(immutModelName)
            .addStatement("return this")
            .build());

    // Add _asBuilder method from ImmutableModel interface
    classBuilder.addMethod(
        methodBuilder("_asBuilder")
            .addAnnotation(Override.class)
            .addModifiers(PUBLIC)
            .returns(ClassName.get("", "Builder"))
            .addStatement("return new Builder(_proto().toBuilder())")
            .build());

    // Add _newCopy method from ImmutableModel interface
    classBuilder.addMethod(
        methodBuilder("_newCopy")
            .addAnnotation(Override.class)
            .addModifiers(PUBLIC)
            .returns(immutableProtoType)
            .addCode(
                """
                if(_serializedPayload != null) {
                  return new $L(_serializedPayload);
                } else if(_proto != null){
                  return new $L(_proto);
                } else {
                  throw new $T("Both _proto and _serializedPayload are null");
                }
                """,
                protoClassName,
                protoClassName,
                IllegalStateException.class)
            .build());

    // Add method to lazily deserialize the proto message
    MethodSpec.Builder getProtoMsgBuilder =
        MethodSpec.overriding(util.getMethod(SerializableProtoModel.class, "_proto", 0))
            .returns(protoMsgType)
            .beginControlFlow("if (_proto == null && _serializedPayload != null)")
            .beginControlFlow("try")
            .addStatement("_proto = $T.parseFrom(_serializedPayload)", protoMsgType)
            .nextControlFlow("catch (Exception e)")
            .addStatement("throw new RuntimeException(\"Failed to deserialize proto message\", e)")
            .endControlFlow()
            .endControlFlow()
            .beginControlFlow("if (_proto == null)")
            .addStatement(
                "throw new IllegalStateException(\"Both _proto and _serializedPayload are null\")")
            .endControlFlow()
            .addStatement("return _proto");

    classBuilder.addMethod(getProtoMsgBuilder.build());

    // Add getters for all model methods
    for (ExecutableElement method : modelMethods) {

      // Get the return type
      TypeMirror returnType = method.getReturnType();
      CodeGenType dataType = new DeclaredTypeVisitor(util, method).visit(returnType);

      classBuilder.addMethod(getterMethod(method, dataType, false).build());
    }

    // Add equals method that delegates to the proto object

    util.addImmutableModelObjectMethods(
        immutModelName,
        modelMethods.stream().map(ExecutableElement::getSimpleName).collect(Collectors.toSet()),
        classBuilder);

    // Add Builder inner class
    TypeSpec builderTypeSpec =
        generateBuilderTypeSpec(
            modelRootType, packageName, protoClassName, protoMsgType, immutModelName, modelMethods);
    classBuilder.addType(builderTypeSpec);
    ClassName immutProtoBuilderClass = immutableProtoType.nestedClass("Builder");
    classBuilder.addMethod(
        methodBuilder("_builder")
            .addModifiers(PUBLIC, STATIC)
            .returns(immutProtoBuilderClass)
            .addStatement("return new $T()", immutProtoBuilderClass)
            .build());
    classBuilder.addMethod(
        methodBuilder("_proto")
            .addModifiers(PUBLIC, STATIC)
            .returns(protoMsgType)
            .addParameter(TypeName.get(modelRootType.asType()), "_model")
            .addCode(
"""
    return _model instanceof $T _immut
        ? _immut._proto()
        : new $T(_model)._proto();
""",
                immutableProtoType,
                immutableProtoType)
            .build());
    classBuilder.addMethod(
        methodBuilder("_proto")
            .addModifiers(PUBLIC, STATIC)
            .returns(protoMsgType.nestedClass("Builder"))
            .addParameter(immutInterfaceName.nestedClass("Builder"), "_builder")
            .addCode(
"""
    return _builder instanceof $T _protoBuilder
        ? _protoBuilder._proto()
        : new $T(_builder._build())._asBuilder()._proto();
""",
                immutProtoBuilderClass,
                immutableProtoType)
            .build());
    return classBuilder.build();
  }

  private MethodSpec copyCtor(List<ExecutableElement> modelMethods) {
    MethodSpec.Builder ctorBuilder = MethodSpec.constructorBuilder().addModifiers(PUBLIC);

    ctorBuilder.addParameter(TypeName.get(codeGenContext.modelRootType().asType()), "_from");

    ctorBuilder.addCode("this._proto = _builder()");
    ctorBuilder.addCode(
        modelMethods.stream()
            .map(
                method -> {
                  boolean isOptional = util.isOptional(method.getReturnType());
                  boolean isNullable = method.getReturnType().getAnnotation(Nullable.class) != null;
                  String methodName = method.getSimpleName().toString();
                  Optional<ModelRootInfo> modelRoot = util.asModelRoot(method.getReturnType());
                  CodeBlock accessor;
                  if (modelRoot.isPresent()) {
                    if (isOptional) {
                      accessor =
                          CodeBlock.of(
                              "($T) _from.$L().map($T::_asBuilder).orElse(null)",
                              util.getImmutInterfaceName(modelRoot.get().element())
                                  .nestedClass("Builder"),
                              methodName,
                              Model.class);
                    } else if (isNullable) {
                      accessor =
                          CodeBlock.of(
                              "($T) $T.ofNullable(_from.$L()).map($T::_asBuilder).orElse(null)",
                              util.getImmutInterfaceName(modelRoot.get().element())
                                  .nestedClass("Builder"),
                              Optional.class,
                              methodName,
                              Model.class);
                    } else {
                      accessor = CodeBlock.of("_from.$L()", methodName);
                    }
                  } else {
                    accessor =
                        CodeBlock.of(
                            "_from.$L()" + (isOptional ? ".orElse(null)" : ""), methodName);
                  }
                  return CodeBlock.of(".$L($L)", methodName, accessor);
                })
            .collect(CodeBlock.joining("")));
    ctorBuilder.addCode("._build()._proto();");
    return ctorBuilder.build();
  }

  private MethodSpec.Builder getterMethod(
      ExecutableElement method, CodeGenType dataType, boolean isBuilder) {
    final TypeMirror specifiedType = method.getReturnType();
    TypeName typeName = TypeName.get(specifiedType);

    String methodName = method.getSimpleName().toString();

    MethodSpec.Builder getterBuilder =
        methodBuilder(methodName).addAnnotation(Override.class).addModifiers(PUBLIC);

    Optional<ModelRootInfo> fieldModelRootInfo = util.asModelRoot(specifiedType);
    if (isBuilder
        && fieldModelRootInfo.isPresent()
        && LIST.equals(fieldModelRootInfo.get().containerType())) {
      ClassName immutInterfaceName = util.getImmutInterfaceName(fieldModelRootInfo.get().element());
      typeName =
          ParameterizedTypeName.get(
              ClassName.get(UnmodifiableModelList.class),
              TypeName.get(fieldModelRootInfo.get().type()),
              immutInterfaceName);
    }

    // Only add @Nullable annotation if the field needs presence check, is not FAIL,
    // and the return type is not Optional
    if (needsPresenceCheckInModels(method)
        && !isMandatoryField(method)
        && !util.isOptional(specifiedType)) {
      typeName = typeName.annotated(AnnotationSpec.builder(Nullable.class).build());
    }

    getterBuilder.returns(typeName);

    addGetterCode(getterBuilder, method, dataType, methodName, isBuilder);
    return getterBuilder;
  }

  private void addGetterCode(
      MethodSpec.Builder getterBuilder,
      ExecutableElement method,
      CodeGenType dataType,
      String fieldName,
      boolean isBuilder) {

    Optional<ModelRootInfo> fieldModelRootInfo = util.asModelRoot(method.getReturnType());
    if (isProtoTypeRepeated(dataType)) {
      if (fieldModelRootInfo.isPresent()) {
        ClassName immutProtoClass =
            util.getImmutClassName(fieldModelRootInfo.get().element(), PROTOBUF_3);
        if (isBuilder) {
          ClassName protoMsgOrBuilderType =
              ClassName.get(
                  immutProtoClass.packageName(),
                  fieldModelRootInfo.get().element().getSimpleName().toString()
                      + MODELS_PROTO_MSG_SUFFIX
                      + "OrBuilder");
          getterBuilder.addStatement(
              CodeBlock.builder()
                  .addNamed(
"""
      return new $protoListBuilder:T<>(
              $modelRoot:T.class,
              $immutIface:T.class,
              $immutIface:T.Builder.class,
              $lists:T.transform(_proto().get$fieldNameCap:LList(), $immutProto:T::new),
              $lists:T.transform(
                  _proto().get$fieldNameCap:LBuilderList(), $immutProto:T.Builder::new),
              _m -> _proto().add$fieldNameCap:L($immutProto:T._proto(_m)),
              _b -> _proto().add$fieldNameCap:L($immutProto:T._proto(_b)),
              (index, _model) ->
                  _proto().add$fieldNameCap:L(index, $immutProto:T._proto(_model)),
              (index, _builder) ->
                  _proto().add$fieldNameCap:L(index, $immutProto:T._proto(_builder)),
              _models -> {
                _proto()
                    .addAll$fieldNameCap:L(
                        $iterables:T.transform(_models, $immutProto:T::_proto));
                return _models.iterator().hasNext();
              },
              _proto()::clear$fieldNameCap:L,
              (index, _model) ->
                  _proto().add$fieldNameCap:L(index, $immutProto:T._proto(_model)),
              (index, _builder) ->
                  _proto().add$fieldNameCap:L(index, $immutProto:T._proto(_builder)),
              index -> {
                $protoMsgOrBuilder:T ret = _proto().get$fieldNameCap:LOrBuilder(index);
                _proto().remove$fieldNameCap:L(index);
                return new $immutProto:T(ret);
              })
          .unmodifiableModelsView()
""",
                      ofEntries(
                          entry("protoListBuilder", ProtoListBuilder.class),
                          entry("modelRoot", fieldModelRootInfo.get().type()),
                          entry(
                              "immutIface",
                              util.getImmutInterfaceName(fieldModelRootInfo.get().element())),
                          entry("immutProto", immutProtoClass),
                          entry("lists", Lists.class),
                          entry("fieldNameCap", capitalizeFirstChar(fieldName)),
                          entry("iterables", Iterables.class),
                          entry("protoMsgOrBuilder", protoMsgOrBuilderType)))
                  .build());
        } else {
          getterBuilder.addStatement(
              "return $T.transform(_proto().get$LList(), $T::new)",
              Lists.class,
              capitalizeFirstChar(fieldName),
              immutProtoClass);
        }
      } else {
        // For repeated fields, use getXList() method
        getterBuilder.addStatement("return _proto().get$LList()", capitalizeFirstChar(fieldName));
      }
      return;
    }

    if (isProtoTypeMap(dataType)) {
      // For map fields, use getXMap() method
      getterBuilder.addStatement("return _proto().get$LMap()", capitalizeFirstChar(fieldName));
      return;
    }
    TypeMirror methodReturnType = method.getReturnType();
    boolean isOptionalReturnType = util.isOptional(methodReturnType);

    // Return null for fields which can be inspected for presence/absence of value
    if (needsPresenceCheckInModels(method)) {
      CodeBlock protoPresenceCheck =
          CodeBlock.of(
              """
              if (!_proto().has$L()){
              """,
              capitalizeFirstChar(fieldName));

      // Add validation for mandatory fields
      if (isMandatoryField(method)) {
        getterBuilder
            .addCode(protoPresenceCheck)
            .addCode(
                """
                throw new $T($S, $S);
              }
              """,
                MandatoryFieldMissingException.class,
                util.getImmutClassName(codeGenContext.modelRootType(), PROTOBUF_3).simpleName(),
                fieldName);
      } else if (isOptionalReturnType) {
        getterBuilder
            .addCode(protoPresenceCheck)
            .addCode(
                """
                return Optional.empty();
              }
              """);
      } else {
        getterBuilder
            .addCode(protoPresenceCheck)
            .addCode(
                """
                return null;
              }
              """);
      }
    }
    CodeBlock creatorCode =
        fieldModelRootInfo
            .map(
                _m ->
                    CodeBlock.of(
                        "new $T(_proto().get$L())",
                        util.getImmutClassName(_m.element(), PROTOBUF_3),
                        capitalizeFirstChar(fieldName)))
            .orElseGet(() -> CodeBlock.of("_proto().get$L()", capitalizeFirstChar(fieldName)));

    // Get the value from the proto message
    if (isOptionalReturnType) {
      getterBuilder.addStatement("return $T.of($L)", Optional.class, creatorCode);
    } else {
      getterBuilder.addStatement("return $L", creatorCode);
    }
  }

  private TypeSpec generateBuilderTypeSpec(
      TypeElement modelRootType,
      String packageName,
      String protoClassName,
      ClassName protoMsgClassName,
      ClassName immutInterfaceName,
      List<ExecutableElement> modelMethods) {
    ModelRoot modelRoot = modelRootType.getAnnotation(ModelRoot.class);

    ClassName immutableProtoType = ClassName.get(packageName, protoClassName);

    // Create class interfaces
    ClassName builderInterfaceClassName = immutInterfaceName.nestedClass("Builder");

    ClassName protoMsgBuilderClassName = protoMsgClassName.nestedClass("Builder");

    // Create Builder class
    Builder builderClassBuilder =
        util.classBuilder("Builder", modelRootType.getQualifiedName().toString())
            .addModifiers(PUBLIC, STATIC)
            .addSuperinterface(builderInterfaceClassName);

    // Add Builder field
    builderClassBuilder.addField(
        FieldSpec.builder(protoMsgBuilderClassName, "_proto", PRIVATE, FINAL).build());

    // Add Builder constructor with _proto parameter
    builderClassBuilder.addMethod(
        MethodSpec.constructorBuilder()
            .addParameter(protoMsgBuilderClassName, "_proto")
            .addStatement("this._proto = _proto")
            .build());

    // Add Builder default constructor
    builderClassBuilder.addMethod(
        MethodSpec.constructorBuilder()
            .addModifiers(PUBLIC)
            .addStatement("this._proto = $T.newBuilder()", protoMsgClassName)
            .build());

    // Add _build method
    builderClassBuilder.addMethod(
        methodBuilder("_build")
            .addAnnotation(Override.class)
            .addModifiers(PUBLIC)
            .returns(immutableProtoType)
            .addStatement("return new $L(_proto.build())", protoClassName)
            .build());

    // Add _asBuilder method
    ClassName builderType = ClassName.get("", "Builder");
    builderClassBuilder.addMethod(
        methodBuilder("_asBuilder")
            .addAnnotation(Override.class)
            .addModifiers(PUBLIC)
            .returns(builderType)
            .addStatement("return this")
            .build());

    // Add _newCopy method
    builderClassBuilder.addMethod(
        methodBuilder("_newCopy")
            .addAnnotation(Override.class)
            .addModifiers(PUBLIC)
            .returns(builderType)
            .addStatement("return new Builder(_proto.clone())")
            .build());

    // Add getters and setters for all model methods
    for (ExecutableElement method : modelMethods) {
      String fieldName = method.getSimpleName().toString();
      TypeMirror returnType = method.getReturnType();
      CodeGenType dataType = new DeclaredTypeVisitor(util, method).visit(returnType);

      Optional<ModelRootInfo> fieldModelRoot = util.asModelRoot(method.getReturnType());
      if (modelRoot.builderExtendsModelRoot()) {
        builderClassBuilder.addMethod(getterMethod(method, dataType, true).build());
      }
      // Add setter method
      MethodSpec.Builder setterBuilder =
          methodBuilder(fieldName)
              .addAnnotation(Override.class)
              .addModifiers(PUBLIC)
              .returns(builderType);

      // Check if the field is a repeated field (List) or a map field
      if (isProtoTypeRepeated(dataType)) {
        // For repeated fields, use clear and addAll pattern
        setterBuilder.addCode(
            """
                _proto.clear$L();
                if ($L == null){
                  return this;
                }
                _proto.addAll$L($L);
              """,
            capitalizeFirstChar(fieldName),
            fieldName,
            capitalizeFirstChar(fieldName),
            fieldModelRoot.isPresent() && LIST.equals(fieldModelRoot.get().containerType())
                ? CodeBlock.of(
"""

          $T.transform(
              $L,
              _element ->
                  _element instanceof $T _proto
                      ? _proto._proto()
                      : _element instanceof $T.Builder _proto
                          ? _proto._proto().build()
                          : new $T(_element)._proto())
""",
                    Lists.class,
                    fieldName,
                    util.getImmutClassName(fieldModelRoot.get().element(), PROTOBUF_3),
                    util.getImmutClassName(fieldModelRoot.get().element(), PROTOBUF_3),
                    util.getImmutClassName(fieldModelRoot.get().element(), PROTOBUF_3))
                : fieldName);
      } else if (isProtoTypeMap(dataType)) {
        // For map fields, use clear and putAll pattern
        setterBuilder.addCode(
            """
                  _proto.clear$L();
                  if ($L == null){
                    return this;
                  }
                  _proto.putAll$L($L);
                """,
            capitalizeFirstChar(fieldName),
            fieldName,
            capitalizeFirstChar(fieldName),
            fieldName);
      } else {
        // For regular fields
        setterBuilder.addCode(
            """
                  if ($L == null){
                    _proto.clear$L();
                    return this;
                  }
                """,
            fieldName,
            capitalizeFirstChar(fieldName));

        if (fieldModelRoot.isPresent()) {
          ClassName fieldProtoClassName =
              util.getImmutClassName(fieldModelRoot.get().element(), PROTOBUF_3);
          setterBuilder.addCode(
"""
      if($L instanceof $T _builder){
        _proto.set$L(_builder._proto());
      } else if($L instanceof $T _immut){
        _proto.set$L(_immut._proto());
      } else {
        _proto.set$L(new $T(($T)$L._build())._proto());
      }
""",
              fieldName,
              fieldProtoClassName.nestedClass("Builder"),
              capitalizeFirstChar(fieldName),
              fieldName,
              fieldProtoClassName,
              capitalizeFirstChar(fieldName),
              capitalizeFirstChar(fieldName),
              fieldProtoClassName,
              fieldModelRoot.get().element(),
              fieldName);
        } else {
          setterBuilder.addStatement(
              dataType.equals(BYTE)
                  ? CodeBlock.of(
                      "_proto.set$L($T.copyFrom(new byte[]{$L}))",
                      capitalizeFirstChar(fieldName),
                      ByteString.class,
                      fieldName)
                  : CodeBlock.of("_proto.set$L($L)", capitalizeFirstChar(fieldName), fieldName));
        }
      }

      setterBuilder.addStatement("return this");

      TypeName variableType = util.getVariableType(method, true);
      MethodSpec setter = setterBuilder.addParameter(variableType, fieldName).build();
      builderClassBuilder.addMethod(setter);

      if (fieldModelRoot.isPresent()
          && !fieldModelRoot.get().annotation().builderExtendsModelRoot()
          && ContainerType.NO_CONTAINER.equals(fieldModelRoot.get().containerType())) {
        builderClassBuilder.addMethod(
            methodBuilder(fieldName)
                .addModifiers(PUBLIC)
                .addParameter(
                    util.getImmutInterfaceName(fieldModelRoot.get().element())
                        .nestedClass("Builder"),
                    fieldName)
                .addAnnotation(Override.class)
                .returns(builderType)
                .addCode(setter.code)
                .build());
      }
    }

    // Add method to access the proto builder
    return builderClassBuilder
        .addMethod(
            methodBuilder("_proto")
                .addModifiers(PUBLIC)
                .returns(protoMsgBuilderClassName)
                .addStatement("return _proto")
                .build())
        .build();
  }

  private boolean needsPresenceCheckInModels(ExecutableElement method) {
    TypeMirror returnType = method.getReturnType();
    CodeGenType dataType = new DeclaredTypeVisitor(util, method).visit(returnType, null);
    if (isProtoTypeRepeated(dataType)) {
      return false;
    }
    if (isProtoTypeMap(dataType)) {
      return false;
    }
    return !util.getIfAbsent(method).value().usePlatformDefault();
  }

  /**
   * Checks if a field should be treated as mandatory. Fields with @IfAbsent(FAIL) are treated as
   * mandatory.
   */
  private boolean isMandatoryField(ExecutableElement method) {
    return util.getIfAbsent(method).value() == IfAbsentThen.FAIL;
  }
}
