package com.flipkart.krystal.vajram.protobuf2024e.codegen;

import com.flipkart.krystal.codegen.common.spi.CodeGenerator;
import com.flipkart.krystal.codegen.common.spi.ModelsCodeGenContext;
import com.flipkart.krystal.codegen.common.spi.ModelsCodeGeneratorProvider;
import com.flipkart.krystal.model.ModelProtocol;
import com.flipkart.krystal.serial.SerializableModel;
import com.flipkart.krystal.vajram.protobuf2024e.Protobuf2024e;
import com.google.auto.service.AutoService;
import java.util.Set;

/**
 * Generates the framework wrapper class for a model that opts into the {@link Protobuf2024e}
 * protocol. The wrapper - named {@code [ModelName]_ImmutProto} - implements the {@code
 * [ModelName]_Immut} interface and {@link SerializableModel}, delegating all getters/setters to a
 * lazily-deserialized {@code [ModelName]_Proto} message produced by protoc from the edition-2024
 * schema generated by {@link Proto2024eSchemaGen}.
 */
@AutoService(ModelsCodeGeneratorProvider.class)
public class Proto2024eModelsGenProvider implements ModelsCodeGeneratorProvider {

  @Override
  public CodeGenerator create(ModelsCodeGenContext codeGenContext) {
    return new Proto2024eModelsGen(codeGenContext);
  }

  @Override
  public Set<Class<? extends ModelProtocol>> getSupportedModelProtocols() {
    return Set.of(Protobuf2024e.class);
  }
}
