description = 'Plugin for the visualization layer for Krystal. Includes static call graph visualizations.'

description = "Generates visualizations of the krystal graph - for example as an HTML"

dependencies {
    api project(':krystex')
    implementation project(':vajram:extensions:json:vajram-json')

    implementation libs.jackson.annotations
    implementation libs.jackson.databind
    implementation libs.jackson.dataformat.yaml

    testImplementation testFixtures(project(':krystex'))
    testImplementation libs.jackson.annotations
    testImplementation libs.jackson.databind
}
