package com.flipkart.krystal.vajram.lang.rust.codegen;

import com.flipkart.krystal.vajram.lang.rust.ast.Completion;
import com.flipkart.krystal.vajram.lang.rust.ast.ComputedFacet;
import com.flipkart.krystal.vajram.lang.rust.ast.DepInputResolver;
import com.flipkart.krystal.vajram.lang.rust.ast.Dependency;
import com.flipkart.krystal.vajram.lang.rust.ast.DependencyInvocation;
import com.flipkart.krystal.vajram.lang.rust.ast.Field;
import com.flipkart.krystal.vajram.lang.rust.ast.InjectionDecl;
import com.flipkart.krystal.vajram.lang.rust.ast.InputDecl;
import com.flipkart.krystal.vajram.lang.rust.ast.OutputBlock;
import com.flipkart.krystal.vajram.lang.rust.ast.VajramDef;
import com.flipkart.krystal.vajram.lang.rust.ast.VajramFile;
import com.flipkart.krystal.vajram.lang.rust.resolve.SymbolTable;
import com.flipkart.krystal.vajram.lang.rust.system.SystemVajram;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import org.jspecify.annotations.Nullable;

/**
 * Emits one Rust source module per Vajram: an inputs struct, an optional deps (injections) struct,
 * and a {@code pub async fn call(...)} entry point. Dependency invocations become calls to other
 * generated modules' {@code call} fns; fanout invocations become {@code
 * futures::future::join_all}/{@code try_join_all}.
 */
public final class RustEmitter {

  private final SymbolTable symbolTable;
  private VajramFile currentFile;

  public RustEmitter(SymbolTable symbolTable) {
    this.symbolTable = symbolTable;
  }

  public String emit(VajramFile file) {
    currentFile = file;
    VajramDef vajram = file.vajram();
    String typeName = Naming.capitalize(vajram.name());
    Set<String> inputNames =
        vajram.inputs().stream().map(InputDecl::name).collect(Collectors.toSet());
    Set<String> injectionNames =
        vajram.injections().stream().map(InjectionDecl::name).collect(Collectors.toSet());
    Set<String> fieldNames =
        vajram.computedFacets().stream()
            .filter(Field.class::isInstance)
            .map(Field.class::cast)
            .map(Field::name)
            .collect(Collectors.toSet());
    Set<String> dependencyNames =
        vajram.computedFacets().stream()
            .filter(Dependency.class::isInstance)
            .map(Dependency.class::cast)
            .map(Dependency::name)
            .collect(Collectors.toSet());
    ExprEmitter exprs = new ExprEmitter(inputNames, injectionNames, fieldNames);

    RustWriter w = new RustWriter();
    w.line("// Generated by vajram-lang-rust-compiler from " + file.sourcePath().getFileName());
    w.line("#![allow(unused)]");
    w.line("use crate::vajram_rt::{Errable, VajramError};");
    w.line("use std::rc::Rc;");
    w.blank();

    emitInputsStruct(w, vajram, typeName);
    boolean hasDeps = !vajram.injections().isEmpty();
    if (hasDeps) {
      emitDepsStruct(w, vajram, typeName);
    }

    Completion completion = symbolTable.completionOf(file);
    if (completion.isAsync()) {
      exprs =
          exprs.withDeferredFacets(
              java.util.stream.Stream.concat(fieldNames.stream(), dependencyNames.stream())
                  .collect(Collectors.toSet()));
    }
    String returnType = TypeMapper.toRustReturnType(vajram.outputType());
    String signature =
        "pub "
            + (completion.isAsync() ? "async " : "")
            + "fn call(inputs: "
            + typeName
            + "Inputs"
            + (hasDeps ? ", deps: Rc<" + typeName + "Deps>" : "")
            + ") -> "
            + returnType;
    w.openBlock(signature);
    for (ComputedFacet facet : vajram.computedFacets()) {
      if (facet instanceof Field field) {
        w.append(emitField(field, exprs, completion, hasDeps));
      } else if (facet instanceof Dependency dependency) {
        w.append(emitDependency(dependency, hasDeps, completion, exprs));
      }
    }
    w.append(emitOutputBlock(vajram.outputBlock(), hasDeps, completion, exprs));
    w.closeBlock();
    return w.toString();
  }

  private void emitInputsStruct(RustWriter w, VajramDef vajram, String typeName) {
    w.openBlock("#[derive(Debug, Clone)]\npub struct " + typeName + "Inputs");
    for (InputDecl input : vajram.inputs()) {
      w.line("pub " + input.name() + ": " + TypeMapper.toRustOwnedType(input.type()) + ",");
    }
    w.closeBlock();
    w.blank();
  }

  private void emitDepsStruct(RustWriter w, VajramDef vajram, String typeName) {
    w.openBlock("pub struct " + typeName + "Deps");
    for (InjectionDecl injection : vajram.injections()) {
      w.line("pub " + injection.name() + ": " + TypeMapper.toRustOwnedType(injection.type()) + ",");
    }
    w.closeBlock();
    w.blank();
  }

  private String emitOutputBlock(
      OutputBlock block, boolean hasDeps, Completion completion, ExprEmitter exprs) {
    if (block instanceof OutputBlock.Logic logic) {
      return exprs.emitOwnedBlockBody(logic.body().statements(), logic.body().yield());
    } else if (block instanceof OutputBlock.Delegate delegate) {
      return emitDelegate(delegate, hasDeps, completion, exprs);
    }
    throw new IllegalStateException("Unhandled output block kind: " + block.getClass());
  }

  private String emitDelegate(
      OutputBlock.Delegate delegate, boolean hasDeps, Completion completion, ExprEmitter exprs) {
    DependencyInvocation invocation = delegate.invocation();
    StringBuilder sb = new StringBuilder();
    for (var block : invocation.extraAnnotatedBlocks()) {
      sb.append("// NOTE: ignoring `")
          .append(String.join(" ", block.annotations()))
          .append("` clause - not modeled by this compiler yet\n");
    }
    String call = emitInvocationCall(invocation, hasDeps, completion, exprs);
    if (invocation.errableFallback() != null) {
      call = call + "." + exprs.emit(invocation.errableFallback());
    }
    sb.append("return ").append(call).append(";");
    return sb.toString();
  }

  private String emitDependency(
      Dependency dependency, boolean hasDeps, Completion completion, ExprEmitter exprs) {
    if (completion.isAsync()) {
      String name = dependency.name();
      ExprEmitter taskExprs = exprs.inTaskScope("_" + name + "_inputs", "_" + name + "_deps");
      return "let _"
          + name
          + "_inputs = inputs.clone();\n"
          + (hasDeps ? "let _" + name + "_deps = Rc::clone(&deps);\n" : "")
          + "let "
          + name
          + " = crate::vajram_rt::spawn_local_shared(async move { "
          + emitInvocationCall(dependency.invocation(), hasDeps, completion, taskExprs)
          + " });\n";
    }
    return "let "
        + dependency.name()
        + " = "
        + emitInvocationCall(dependency.invocation(), hasDeps, completion, exprs)
        + ";";
  }

  private String emitField(Field field, ExprEmitter exprs, Completion completion, boolean hasDeps) {
    if (completion.isAsync()) {
      String name = field.name();
      ExprEmitter taskExprs = exprs.inTaskScope("_" + name + "_inputs", "_" + name + "_deps");
      return "let _"
          + name
          + "_inputs = inputs.clone();\n"
          + (hasDeps ? "let _" + name + "_deps = Rc::clone(&deps);\n" : "")
          + "let "
          + name
          + " = crate::vajram_rt::spawn_local_shared(async move { Rc::new("
          + taskExprs.emit(field.value())
          + ") });\n";
    }
    return "let " + field.name() + " = " + exprs.emit(field.value()) + ";";
  }

  private String emitInvocationCall(
      DependencyInvocation invocation,
      boolean hasDeps,
      Completion callerCompletion,
      ExprEmitter exprs) {
    VajramFile callee = symbolTable.lookup(invocation.vajramName());
    String calleeModule = calleeModule(callee, invocation.vajramName());
    String calleeType = Naming.capitalize(invocation.vajramName());
    boolean calleeErrable = isCalleeErrable(invocation.vajramName());
    String depsArg = hasDeps ? ", Rc::clone(&" + exprs.depsRoot() + ")" : "";

    var systemVajram = SystemVajram.lookup(invocation.vajramName(), currentFile.imports());
    if (systemVajram.isPresent()) {
      return switch (systemVajram.get()) {
        case READ_FILE_AS_STRING -> emitReadFileAsString(invocation, exprs);
        case CONCAT_STRINGS -> emitConcatStrings(invocation, exprs);
      };
    }

    DepInputResolver fannedResolver = findFanned(invocation);
    if (fannedResolver == null) {
      List<String> fieldList = new ArrayList<>();
      for (DepInputResolver resolver : invocation.resolvers()) {
        fieldList.addAll(fieldAssignments(resolver, exprs));
      }
      String fields = String.join(", ", fieldList);
      String call =
          calleeModule
              + "::call("
              + calleeModule
              + "::"
              + calleeType
              + "Inputs { "
              + fields
              + " }"
              + depsArg
              + ")";
      return asyncInvocation(call, invocation.vajramName(), calleeErrable);
    }

    String fannedField =
        fannedResolver.targetInputs().isEmpty() ? "value" : fannedResolver.targetInputs().get(0);
    String fannedExpr = resolverValueTexts(fannedResolver, exprs).stream().findFirst().orElse("[]");
    if (fannedResolver instanceof DepInputResolver.Stat stat
        && stat.values().size() == 1
        && stat.values().get(0)
            instanceof com.flipkart.krystal.vajram.lang.rust.ast.Expr.VarUse varUse
        && exprs.isFieldName(varUse.name())) {
      fannedExpr += ".as_ref().clone()";
    }
    List<String> otherFields = new ArrayList<>();
    for (DepInputResolver resolver : invocation.resolvers()) {
      if (resolver != fannedResolver) {
        otherFields.addAll(fieldAssignments(resolver, exprs));
      }
    }
    String restFields = otherFields.isEmpty() ? "" : ", " + String.join(", ", otherFields);
    String joiner = calleeErrable ? "try_join_all" : "join_all";
    String fanoutCall =
        calleeModule
            + "::call("
            + calleeModule
            + "::"
            + calleeType
            + "Inputs { "
            + fannedField
            + ": Rc::new(it)"
            + restFields
            + " }"
            + depsArg
            + ")";
    if (callee != null && symbolTable.completionOf(callee).isAsync()) {
      fanoutCall += ".await";
    }
    String call =
        "futures::future::"
            + joiner
            + "("
            + fannedExpr
            + ".into_iter().map(|it| async move { "
            + fanoutCall
            + " })).await"
            + (calleeErrable ? "?" : "");
    return call;
  }

  private static String calleeModule(@Nullable VajramFile callee, String vajramName) {
    if (callee == null) {
      return Naming.toSnakeCase(vajramName);
    }
    String packagePath =
        callee.packageSegments().stream()
            .map(Naming::toSnakeCase)
            .collect(Collectors.joining("::"));
    return "crate::"
        + (packagePath.isEmpty() ? "" : packagePath + "::")
        + Naming.toSnakeCase(callee.vajram().name());
  }

  private String asyncInvocation(String call, String vajramName, boolean calleeErrable) {
    VajramFile callee = symbolTable.lookup(vajramName);
    if (callee == null || !symbolTable.completionOf(callee).isAsync()) {
      return call + (calleeErrable ? "?" : "");
    }
    return call + ".await";
  }

  private String emitReadFileAsString(DependencyInvocation invocation, ExprEmitter exprs) {
    for (DepInputResolver resolver : invocation.resolvers()) {
      if (resolver instanceof DepInputResolver.Stat stat
          && stat.targetInputs().size() == 1
          && "path".equals(stat.targetInputs().get(0))
          && stat.values().size() == 1) {
        String path = exprs.emit(stat.values().get(0));
        return "tokio::fs::read_to_string("
            + path
            + ".as_str()"
            + ").await.expect(\"readFileAsString failed\")";
      }
    }
    throw new IllegalArgumentException("readFileAsString requires exactly one path resolver");
  }

  private String emitConcatStrings(DependencyInvocation invocation, ExprEmitter exprs) {
    String strings = null;
    String separator = null;
    for (DepInputResolver resolver : invocation.resolvers()) {
      if (resolver instanceof DepInputResolver.Stat stat) {
        int count = Math.min(stat.targetInputs().size(), stat.values().size());
        for (int i = 0; i < count; i++) {
          if ("strings".equals(stat.targetInputs().get(i))) {
            strings = exprs.emit(stat.values().get(i));
          } else if ("separator".equals(stat.targetInputs().get(i))) {
            separator = exprs.emit(stat.values().get(i));
          }
        }
      }
    }
    if (strings == null || separator == null) {
      throw new IllegalArgumentException(
          "concatStrings requires exactly one strings resolver and one separator resolver");
    }
    return "Rc::new("
        + strings
        + ".iter().map(|value| value.as_str()).collect::<Vec<_>>().join("
        + separator
        + ".as_str()))";
  }

  private @Nullable DepInputResolver findFanned(DependencyInvocation invocation) {
    for (DepInputResolver resolver : invocation.resolvers()) {
      if (resolver.fanout()) {
        return resolver;
      }
    }
    return invocation.fanout() && !invocation.resolvers().isEmpty()
        ? invocation.resolvers().get(0)
        : null;
  }

  private List<String> fieldAssignments(DepInputResolver resolver, ExprEmitter exprs) {
    List<String> targets = resolver.targetInputs();
    List<String> values = resolverValueTexts(resolver, exprs);
    List<String> result = new ArrayList<>();
    int n = Math.min(targets.size(), values.size());
    for (int i = 0; i < n; i++) {
      result.add(targets.get(i) + ": " + ownedValue(values.get(i), resolver, i, exprs));
    }
    return result;
  }

  private List<String> resolverValueTexts(DepInputResolver resolver, ExprEmitter exprs) {
    if (resolver instanceof DepInputResolver.Stat stat) {
      return stat.values().stream().map(exprs::emit).toList();
    } else if (resolver instanceof DepInputResolver.Func func) {
      return List.of(
          "{ " + exprs.emitBlockBody(func.body().statements(), func.body().yield()) + " }");
    }
    throw new IllegalStateException("Unhandled resolver kind: " + resolver.getClass());
  }

  private String ownedValue(String value, DepInputResolver resolver, int index, ExprEmitter exprs) {
    if (resolver instanceof DepInputResolver.Stat stat
        && stat.values().get(index)
            instanceof com.flipkart.krystal.vajram.lang.rust.ast.Expr.VarUse varUse
        && !exprs.isFieldName(varUse.name())
        && !exprs.isDeferredFacetName(varUse.name())) {
      return "Rc::clone(&" + value + ")";
    }
    if (resolver instanceof DepInputResolver.Stat stat
        && stat.values().get(index)
            instanceof com.flipkart.krystal.vajram.lang.rust.ast.Expr.VarUse varUse
        && exprs.isDeferredFacetName(varUse.name())) {
      return value;
    }
    return "Rc::new(" + value + ")";
  }

  private boolean isCalleeErrable(String vajramName) {
    VajramFile callee = symbolTable.lookup(vajramName);
    return callee != null && callee.vajram().outputType().errable();
  }
}
